config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :original_text, presence: true
  validates :translated_text, presence: true

  validate :original_text_cannot_be_equal_to_translated_text

  before_create do
    self.review_date = Date.today + 3
  end

  def original_text_cannot_be_equal_to_translated_text
    errors.add(:equally, "can't be equal") if original_text.casecmp?(translated_text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :init_card, only: %i[show edit update destroy]
  def index
    @cards = Card.all
  end

  def show; end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render action: 'new'
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render action: 'edit'
    end
  end

  def destroy
    @card.destroy

    redirect_to cards_path
  end

  private

  def init_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/edit.html.haml
%h1= t :new_card

= simple_form_for @card, :url => { :action => "update" } do |f|
  = f.input :original_text
  = f.input :translated_text
  = f.button :submit

app/views/cards/index.html.haml
%ul
  - @cards.each do |card|
    %li
      = link_to "#{card.original_text}", card_path(card)
      = link_to 'Edit', edit_card_path(card)
      = link_to 'Delete', card_path(card), method: :delete

app/views/cards/new.html.haml
%h1= t :new_card

= simple_form_for @card, :url => { :action => "create" } do |f|
  = f.input :original_text
  = f.input :translated_text
  = f.button :submit

app/views/cards/show.html.haml
%h3= t :original

%p= @card.original_text

%h3= t :translate

%p= @card.translated_text

%h3= t :review

%p= @card.review_date

app/views/home/index.html.haml
%p{:style => "font-size: 22px;"}
  =t :about

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title=t :name
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %section#container
      %header.clearfix
        %h1=t :name
        %ul.navigation-links
          %li
            = link_to "#{t :all_cards}", cards_path
          %li
            = link_to "#{t :add_card}", new_card_path
      %section
        = yield